name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install nox
      - run: nox -s lint
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install nox
      - run: nox -s release -- --version '' --repo '' --prebump ''
  test:
    name: Test
    runs-on: ubuntu-20.04
    needs: [lint]
    strategy:
      fail-fast: true
      matrix:
        python:
          - "2.7"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: pip install nox
      - run: nox -s tests-${{ matrix.python }}
